### ISSUE TITLE
v2.8.0: klass.create is not a function

### ISSUE THREAD

**Issue by tsteuwer** [sir-dunxalot/ember-tooltips#166]
After a fresh install via ``ember install`` and using the following code:

```
<span>
   {{#tooltip-on-element enableLazyRendering=true}}
      Hello 
   {{/tooltip-on-element}}
</span>
```

I get the following deprecation and exception:

```
DEPRECATION: In Ember 2.0 component factories must have an `isComponentFactory` property set to true. You registered [object Object] as a component factory. Either add the `isComponentFactory` property to this factory or extend from Ember.Component. [deprecation id: ember-application.validate-type]
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:16770:19)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16881:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16800:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16881:7)
        at invoke (http://localhost:4200/assets/vendor.js:16897:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16865:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:27884:37)
        at Object.validateType [as default] (http://localhost:4200/assets/vendor.js:16574:19)
        at Class.resolve (http://localhost:4200/assets/vendor.js:16282:51)
ember.debug.js:12048 Uncaught TypeError: klass.create is not a function
```

My versions:

ember-tooltips: 2.8.0
ember-cli: 2.10.0
http_parser: 2.7.0
node: 6.0.0
v8: 5.0.71.35
uv: 1.9.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2g
os: linux x64
3.8.6

**Comment by admxxi** [comment]
I was trying to run ember-light-table and then I got this error message

TypeError: klass.create is not a function
    at CurlyComponentManager.create (ember.debug.js:12591)
    at OpenComponentOpcode.evaluate (ember.debug.js:47198)
    at VM.execute (ember.debug.js:53789)
    at VM.resume (ember.debug.js:53768)
    at TryOpcode.handleException (ember.debug.js:54279)
    at UpdatingVMFrame.handleException (ember.debug.js:54459)
    at UpdatingVM._throw [as throw] (ember.debug.js:54172)
    at Assert.evaluate (ember.debug.js:49541)
    at UpdatingVM.execute (ember.debug.js:54159)
    at RenderResult.rerender (ember.debug.js:54098)
defaultDispatch @ ember.debug.js:17636
dispatchError @ ember.debug.js:17615
invokeWithOnError @ ember.debug.js:349
flush @ ember.debug.js:405
flush @ ember.debug.js:529
end @ ember.debug.js:599
run @ ember.debug.js:713
join @ ember.debug.js:744
run.join @ ember.debug.js:22291
hash.error @ rest.js:956
fire @ jquery.js:3317
fireWith @ jquery.js:3447
done @ jquery.js:9274
(anonymous) @ jquery.js:9506
09:59:39.619 jquery.js:9566 OPTIONS http://frontend.app:3000/dashboards/3 net::ERR_CONNECTION_REFUSED
send @ jquery.js:9566
ajax @ jquery.js:9173
_ajaxRequest @ rest.js:969
(anonymous) @ rest.js:959
initializePromise @ ember.debug.js:58580
Promise @ ember.debug.js:59068
ajax @ rest.js:942
findRecord @ rest.js:421
_find @ finders.js:22
_fetchRecord @ store.js:640
_fetchRecord @ store.js:700
_flushPendingFetchForType @ store.js:800
cb @ ember.debug.js:19267
forEach @ ember.debug.js:19072
forEach @ ember.debug.js:19275
flushAllPendingFetches @ store.js:680
invokeWithOnError @ ember.debug.js:346
flush @ ember.debug.js:405
flush @ ember.debug.js:529
end @ ember.debug.js:599
run @ ember.debug.js:713
_runExpiredTimers @ ember.debug.js:1107
Backburner._boundRunExpiredTimers @ ember.debug.js:568

My versions:

Node 6.9.5
Ember-cli / Source / Data 2.12

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
